### ISSUE TITLE
App crashing on load

### ISSUE THREAD

**Issue by rahul69x** [netless-io/flat-android#1]
E/linker: "/data/app/~~RmvzG0ayhtt_jI35aRLZ6g==/io.agora.flat-2phtGLAq2-f68FmwpBJOmQ==/base.apk!/lib/x86/libagora-ffmpeg.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.agora.flat, PID: 6479
    java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~RmvzG0ayhtt_jI35aRLZ6g==/io.agora.flat-2phtGLAq2-f68FmwpBJOmQ==/base.apk!/lib/x86/libagora-ffmpeg.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at io.agora.rtc.internal.RtcEngineImpl.loadNativeLibrary(RtcEngineImpl.java:140)
        at io.agora.rtc.internal.RtcEngineImpl.initializeNativeLibs(RtcEngineImpl.java:200)
        at io.agora.rtc.RtcEngine.create(RtcEngine.java:42)
        at io.agora.flat.di.impl.RtcApiImpl.init(RtcApiImpl.kt:22)
        at io.agora.flat.MainApplication.onCreate(MainApplication.kt:18)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process: Sending signal. PID: 6479 SIG: 9

**Comment by aderan** [comment]
@rahul69x this issue has been fixed in the commit [72d1b94](https://github.com/netless-io/flat-android/commit/72d1b9433c666bc76533bb9707e77098c0fd3c40). By the way, now we need avd with android version 26 or higher.

**Comment by rahul69x** [comment]
@aderan Thanks, It's working now.
